/*
 * dispexmp.c - display test file
 *
 * \author Richard M. Murray
 * \date 12/2/87
 *
 * This file is an example of how to use the sparrow display and debugging
 * routines.  In addition to this file, you need to look at the dispexmp.dd
 * file, where the display is defined.
 *
 * Copyright (c) 2008 by California Institute of Technology
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 
 * 3. Neither the name of the California Institute of Technology nor
 *    the names of its contributors may be used to endorse or promote
 *    products derived from this software without specific prior
 *    written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL CALTECH
 * OR THE CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * $Id$
 */

#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include "display.h"			/* normally sparrow/display.h */
#include "errlog.h"			/* normally sparrow/errlog.h */
#include "dbglib.h"			/* normally sparrow/debug.h */

/* Global variables */
int time_spent;			/* Seconds spent inside program */
int ival, ival_c;		/* integer values (orig and callback) */
double dval, dval_c;		/* double values (orig and callback) */

/* Now include display table (after globals are declared) */
#include "dispexmp.h"		/* display table (generated by cdd) */

int main(int argc, char **argv)
{
    /* Initialize the display package */
    if (dd_open() < 0) exit(1);		/* initialize the database, screen */

    /* Generate some output to test stderr redirection */
    fprintf(stderr, "dispexmp: started; output redirected to dispexmp.log\n");

    /* Now set up an error log (previous message should not be included) */
    dd_errlog_init(10);
    dd_errlog_bindkey();

    /* Rebind some keys and variable values */
    dd_bindkey('Q', user_quit);
    dd_rebind_tbl("ival_c", &ival_c, display);
    dd_rebind_tbl("dval-2", &dval, display);
    dd_usetbl(display);			/* set display description table */

    /* User initialization goes here */
    dbg_flag = 1;			/* turn on debugging */
    dbg_openlog("dispexmp.log", "w");	/* open log file */
    dbg_logf = DBG_INFO | DBG_WARN;	/* set messages we want */
    dbg_outf = ~DBG_INFO;		/* everything except info */
    dbg_add_module("dispexmp.c");	/* log messages in this file */

    /* Pass control to the display manager */
    dd_loop();				/* Start the display manager */
    dd_close();				/* clear the screen and free memory */

    /* User cleanup goes here */
    dbg_closelog();			/* close the log file */

    return 0;
}

/* Callbacks */
int toggle_onoff(long arg) {
  static int flag = 0;
  flag = !flag;
  dd_setcolor(ONOFF, BLACK, flag ? GREEN : RED);
  return 0; 
}
int user_quit(long arg) { return DD_EXIT_LOOP; }
int graph_data(long arg) { return 0; }
int capture_data(long arg) { return 0; }
int dump_data(long arg) { return 0; }

int ival_callback(long arg) {
  dbg_info("ival_callback executed");
  ival_c = ival;
  if (ival < 0) dbg_warn("ival_callback - negative number %d", ival);
  return 0; 
}

int dval_callback(long arg) {
  dbg_info("dval_callback executed");
  dval_c = dval; 
  return 0; 
}

/* Display function for time spent in program */
int user_clock(DD_ACTION action, int arg)
{
    static int init = 0;
    static long start_time, cur_time;

    /* Initialize the first time through */
    if (!init) {
	/* get the current value of system clock */
	start_time = time(NULL);

	++init;
    }

    /* update the current clock value */
    cur_time = time(NULL);
    time_spent = (int) (cur_time - start_time);

    /* Generate an error message every 10 seconds */
    static int last_time_spent = 0;	/* print message once per iteration */
    if ((time_spent % 5) == 0 && last_time_spent != time_spent) {
      fprintf(stderr, "dispexmp: time_spent = %d\n", time_spent);
      last_time_spent = time_spent;
    }

    /* now just use the usual integer display routine */
    return dd_short(action, arg);
}
